### ISSUE TITLE
Face recognition based attendance system

### ISSUE THREAD

**Issue by amulyaashetty** [Tech-Matrix/Face-Recognition-System#3]
**Is your feature request related to a problem? Please describe.**
The present project can recognize only few images so I would like to create an attendance system using face recognition.

**Describe the solution you'd like**
An attendance system with the help of open cv , haarcascade , pandas.

**Describe alternatives you've considered**
1)This face recognition system is trained to click the picture of the faces in the frame of the webcam 
2)With the help of the recognized face an attendance system is created with gui features

**Additional context**
![123](https://user-images.githubusercontent.com/79209035/134656927-d3795a56-9d68-4021-87d6-5168a34948ee.PNG)

**Comment by charvibannur** [comment]
@amulyaashetty would you like to be assigned to this?

**Comment by amulyaashetty** [comment]
@charvibannur Yes, Please assign this to me

**Comment by charvibannur** [comment]
@amulyaashetty I've assigned it.
